CREATE TABLE activities_comments (ID BIGINT NOT NULL, activities_id BIGINT, comments VARCHAR(4096), convenience INTEGER, interesting_rate INTEGER, popularity INTEGER, PRIMARY KEY (ID))
CREATE TABLE activities (id BIGINT AUTO_INCREMENT NOT NULL, abstract_content VARCHAR(255), address VARCHAR(255), city_code INTEGER, convenience INTEGER, end_time DATE, fee BIGINT, gmt_create DATETIME, gmt_modified DATETIME, images VARCHAR(4096), interesting_rate INTEGER, latitude DOUBLE, longitude DOUBLE, popularity INTEGER, scale INTEGER, start_time DATE, tags VARCHAR(256), title VARCHAR(255), activity_type INTEGER, PRIMARY KEY (id))
CREATE TABLE event_crawl_origin (ID BIGINT AUTO_INCREMENT NOT NULL, ABSTRACTCONTENT LONGTEXT, EVENTADDRESS VARCHAR(255), EVENTDATE VARCHAR(255), TITLE VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE users (ID BIGINT AUTO_INCREMENT NOT NULL, avatar VARCHAR(255), cell_phone VARCHAR(255), city INTEGER, email VARCHAR(255), latitude DOUBLE, longitude DOUBLE, password VARCHAR(255), qq INTEGER, role VARCHAR(255), user_name VARCHAR(255), weibo VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE tags (ID BIGINT NOT NULL, tag VARCHAR(255), category_id BIGINT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE tag_category (ID BIGINT NOT NULL, category VARCHAR(255), PRIMARY KEY (ID))
ALTER TABLE tags ADD CONSTRAINT FK_tags_category_id FOREIGN KEY (category_id) REFERENCES tag_category (ID)
